FOLDERS_EMAIL = [
    'APOYO DPE',
    # 'Archivo',
    'Bandeja de entrada',
    # 'Bandeja de salida',
    # 'Borradores',
    'C1-C2',
    'Calidad_CMRN',
    'CODIFICACION_ANLA',
    # 'COMUNICACIONES_ANLA',
    # 'Correo no deseado',
    # 'Elementos eliminados',
    # 'Elementos enviados',
    # 'ELIMINAR',
    # 'ERRORES_ALGORITMOS',
    # 'Fuentes RSS',
    # 'GITHUB',
    'HIDROITUANGO', # Tiene hijos
    # 'Historial de conversaciones',
    'LAM0005-La Miel',
    'LAM0019-Rubiales',
    'LAM0027_La Loma_Drummond',
    'LAM0209_DORADO_REPORTES_SVCR',
    'LAM0237_Hidrosogamoso', # Tiene hijo
    'LAM0666',
    'LAM0761 Refineria',
    'LAM1094-Cerrejon',
    'LAM3271_El Descanso',
    'LAM3352-Embalse Tomine',
    'LAM3888-Calderas',
    'LAM4340',
    'LAV0008-00-2022-Geopark',
    'LAV0029-2016',
    # 'not-verified',
    'Pendientes_Actualizar',
    'PermisosTramite_SIPTA',
    'Portal_Recepcion',
    # 'Pospuesto',
    # 'Problemas de sincronización',
    'QUIMBO-BETANIA',
    'REDIRECCIÓN',
    # 'respuestas a reporte condiciones hidrometeorologicas',
    # 'SST_ANLA',
    'SVCA_GUAJIRA',
    'TOMINE/SESQUILE'
]

EXCLUDED_EXTS = ('.png', '.jpg', '.jpeg', '.gif')